"""
Application Constants
"""

# Signal Types
SIGNAL_LONG = "LONG"
SIGNAL_SHORT = "SHORT"
SIGNAL_NEUTRAL = "NEUTRAL"

# Signal Statuses
STATUS_OPEN = "OPEN"
STATUS_CLOSED = "CLOSED"
STATUS_EXPIRED = "EXPIRED"

# Outcome Types
OUTCOME_WIN = "WIN"
OUTCOME_LOSS = "LOSS"
OUTCOME_NEUTRAL = "NEUTRAL"
OUTCOME_PENDING = "PENDING"

# EMA Periods
EMA_FAST = 9
EMA_MEDIUM = 21
EMA_SLOW = 50
EMA_TREND = 200

# RSI Settings
RSI_PERIOD = 14

# Volume Settings
VOLUME_MA_PERIOD = 20

# Risk/Reward
DEFAULT_RISK_REWARD_RATIO = 2.0

# Time Windows
SIGNAL_EXPIRY_HOURS = 24
TRACKING_WINDOW_HOURS = 72

# Confidence Weights
WEIGHT_TREND = 0.30
WEIGHT_MOMENTUM = 0.25
WEIGHT_VOLUME = 0.20
WEIGHT_LIQUIDITY = 0.15
WEIGHT_FUNDING = 0.10
